# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'easyPlant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for easyPlant

  pod 'FSCalendar'
  pod 'Charts'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'SwiftyJSON'

  target 'easyPlantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'easyPlantUITests' do
    # Pods for testing
  end

end
